#!/usr/bin/env python
# -*- coding: utf-8 -*-
''' This module is all about the coding basics...

Things like math, assignments, splitting, stripping...
replacing, finding the length, indexing....
changing characters to upper and lower case, true, false....
lots of things'''

SPANISH = '''Nobody expects the Spanish Inquisition!
Our chief weapon is surprise...surprise and fear...fear and surprise....
Our two weapons are fear and surprise...and ruthless efficiency....
Our three weapons are fear, surprise, and ruthless efficiency... .
and an almost fanatical devotion to the Pope....
Our four...no... amongst our weapons....
amongst our weaponry are such elements as fear, surprise....
I'll come in again.'''